import { 
  Eraser, 
  ImageOff, 
  Mic, 
  FileText, 
  Receipt, 
  QrCode, 
  RefreshCcw, 
  Sparkles, 
  Image, 
  Search, 
  PenTool, 
  Hash, 
  Moon, 
  Flame, 
  Hourglass, 
  TrendingUp, 
  PieChart 
} from 'lucide-react';
import { Tool, Translation } from './types';

export const TOOLS: Tool[] = [
  { id: 1, nameKey: "bgRemover", icon: Eraser, color: "text-blue-400", isHot: true, span: "col-span-2 row-span-2" },
  { id: 3, nameKey: "watermark", icon: ImageOff, color: "text-red-400" },
  { id: 4, nameKey: "transcriber", icon: Mic, color: "text-green-400" },
  { id: 5, nameKey: "cvBuilder", icon: FileText, color: "text-yellow-400" },
  { id: 6, nameKey: "invoice", icon: Receipt, color: "text-purple-400" },
  { id: 7, nameKey: "qrArt", icon: QrCode, color: "text-pink-400", isNew: true },
  { id: 9, nameKey: "converter", icon: RefreshCcw, color: "text-orange-400" },
  { id: 11, nameKey: "viral", icon: Sparkles, color: "text-indigo-400" },
  { id: 12, nameKey: "thumbnail", icon: Image, color: "text-teal-400" },
  { id: 13, nameKey: "seo", icon: Search, color: "text-cyan-400" },
  { id: 14, nameKey: "logo", icon: PenTool, color: "text-emerald-400", span: "col-span-2" },
  { id: 15, nameKey: "hashtag", icon: Hash, color: "text-sky-400" },
  { id: 16, nameKey: "dream", icon: Moon, color: "text-violet-400" },
  { id: 19, nameKey: "roast", icon: Flame, color: "text-rose-500", isHot: true },
  { id: 20, nameKey: "aging", icon: Hourglass, color: "text-amber-400" },
  { id: 24, nameKey: "arbitrage", icon: TrendingUp, color: "text-lime-400" },
  { id: 25, nameKey: "expense", icon: PieChart, color: "text-fuchsia-400" },
];

export const I18N: Translation = {
  en: {
    headline: "The Only Tool You Need",
    subheadline: "Replace 17 different subscriptions with one powerful AI Super App. Join 10,000+ creators saving time and money.",
    weekly: "Weekly",
    monthly: "Monthly",
    lifetime: "Lifetime",
    unlock: "Unlock Full Access",
    trial: "Test Free Version (With Ads)",
    dashboardTitle: "Your Tools",
    modalStart: "Generate",
    modalClose: "Close",
    bgRemover: "Bg Remover",
    watermark: "Watermark Remover",
    transcriber: "Audio Transcriber",
    cvBuilder: "CV Builder",
    invoice: "Invoice Gen",
    qrArt: "QR Art",
    converter: "File Convert",
    viral: "Viral Caption",
    thumbnail: "Thumbnail AI",
    seo: "SEO Writer",
    logo: "Logo Maker",
    hashtag: "Hashtag Analytics",
    dream: "Dream Interpreter",
    roast: "Roast Profile",
    aging: "Aging AI",
    arbitrage: "Arbitrage",
    expense: "Expense Tracker",
    accessRequired: "Access Required",
    accessMsg: "Please upgrade to use this premium feature.",
    back: "Back",
    maintenance: "Maintenance - Server Busy",
    maintenanceDesc: "We are scaling our GPU clusters. Try again later.",
    inputPlaceholder: "Type here...",
    generating: "Generating...",
    result: "Result",
    copy: "Copy Text",
    // New Landing Page Translations
    usersActive: "Active Users",
    toolsGenerated: "Tools Generated",
    trustedBy: "Trusted by top creators",
    feature1Title: "All-in-One Powerhouse",
    feature1Desc: "Why pay for 17 apps when you can have one? Save over $200/month.",
    feature2Title: "Powered by Gemini 2.5",
    feature2Desc: "Experience the latest in Google AI technology for text and analysis.",
    feature3Title: "Privacy First",
    feature3Desc: "Your data is processed securely and never shared with third parties.",
    review1: "This app saved me hours on my content creation workflow. The SEO writer is insane!",
    review2: "Finally, an app that actually does what it says. The Roast feature is hilarious.",
    faqTitle: "Frequently Asked Questions",
    faq1Q: "Is the payment one-time?",
    faq1A: "Yes! If you choose the Lifetime plan, you pay once and own it forever.",
    faq2Q: "Can I cancel subscription?",
    faq2A: "Absolutely. You can manage your subscription directly in the app settings.",
    bestValue: "BEST VALUE",
    mostPopular: "POPULAR",
    ctaTitle: "Ready to Supercharge?",
    ctaDesc: "Get instant access to all 17+ tools now.",
    securePayment: "Secure Crypto Payment via OxaPay",
  },
  pt: {
    headline: "A Única Ferramenta que Você Precisa",
    subheadline: "Substitua 17 assinaturas diferentes por um Super App de IA poderoso. Junte-se a +10.000 criadores economizando tempo.",
    weekly: "Semanal",
    monthly: "Mensal",
    lifetime: "Vitalício",
    unlock: "Desbloquear Acesso Total",
    trial: "Testar Versão Gratuita (Com Anúncios)",
    dashboardTitle: "Suas Ferramentas",
    modalStart: "Gerar",
    modalClose: "Fechar",
    bgRemover: "Removedor Fundo",
    watermark: "Remove Marca D'água",
    transcriber: "Transcritor Áudio",
    cvBuilder: "Criador CV",
    invoice: "Gerador Fatura",
    qrArt: "QR Code Arte",
    converter: "Conversor Arq.",
    viral: "Legenda Viral",
    thumbnail: "Miniatura IA",
    seo: "Escritor SEO",
    logo: "Criador Logo",
    hashtag: "Análise Hashtag",
    dream: "Interpretar Sonhos",
    roast: "Zuar Perfil",
    aging: "Envelhecimento IA",
    arbitrage: "Arbitragem",
    expense: "Rastreador Gastos",
    accessRequired: "Acesso Necessário",
    accessMsg: "Por favor, faça o upgrade para usar este recurso premium.",
    back: "Voltar",
    maintenance: "Em Manutenção - Servidor Ocupado",
    maintenanceDesc: "Estamos escalando nossos clusters de GPU. Tente novamente mais tarde.",
    inputPlaceholder: "Digite aqui...",
    generating: "Gerando...",
    result: "Resultado",
    copy: "Copiar Texto",
    // Traduções Nova Landing Page
    usersActive: "Usuários Ativos",
    toolsGenerated: "Ferramentas Geradas",
    trustedBy: "Confiado por grandes criadores",
    feature1Title: "Central de Comando",
    feature1Desc: "Por que pagar por 17 apps quando você pode ter um? Economize +R$500/mês.",
    feature2Title: "Poder do Gemini 2.5",
    feature2Desc: "Experimente a última tecnologia de IA do Google para textos e análises.",
    feature3Title: "Privacidade Primeiro",
    feature3Desc: "Seus dados são processados com segurança e nunca compartilhados.",
    review1: "Esse app me economizou horas na criação de conteúdo. O escritor SEO é insano!",
    review2: "Finalmente um app que faz o que promete. A função de Zuar Perfil é hilária.",
    faqTitle: "Perguntas Frequentes",
    faq1Q: "O pagamento é único?",
    faq1A: "Sim! Se escolher o plano Vitalício, paga uma vez e é seu para sempre.",
    faq2Q: "Posso cancelar?",
    faq2A: "Com certeza. Você gerencia sua assinatura nas configurações do Telegram.",
    bestValue: "MELHOR VALOR",
    mostPopular: "POPULAR",
    ctaTitle: "Pronto para Evoluir?",
    ctaDesc: "Tenha acesso instantâneo a todas as 17+ ferramentas agora.",
    securePayment: "Pagamento Cripto Seguro via OxaPay",
  }
};